tool: AutoDock Vina
branch: tool/autodock-vina

score_direction: lower_is_better
score_unit: kcal/mol

box:
  mode: defined
  center_xyz: [70.83, 71.96, 59.18]
  size_xyz: [21.3, 19.6, 27.3]

exhaustiveness: 16
num_poses: 9
scoring_function: vina
random_seed: 42
extra: {}
